Repository milvus-io/milvus-operator, pull requests merged in 2021-11, with the labels that each got.

#24 Add publish by tag workflow, add publish Dockerfile
  .github/workflows/docker-image.yml
  Dockerfile
Labels: lgtm, approved

#25 Bump DefaultMilvusVersion to v2.0.0-rc8
  config/samples/milvuscluster_resource.yaml
  docs/CRD/milvus-cluster.md
  pkg/config/config.go
Labels: lgtm, approved

#26 Add component config & update doc
  api/v1alpha1/configs_types.go
  api/v1alpha1/milvuscluster_types.go
  api/v1alpha1/milvuscluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/assets/templates/component.yaml.tmpl
  config/crd/bases/milvus.io_milvusclusters.yaml
  docs/CRD/milvus-cluster.md
  pkg/config/config.go
  pkg/controllers/components.go
  pkg/controllers/configmaps.go
  pkg/controllers/deployments.go
  pkg/controllers/status.go
Labels: lgtm, approved

#29 Fix milvuscluster CR config sample
  config/samples/milvuscluster_config.yaml
Labels: lgtm, approved

#30 Revert component config
  api/v1alpha1/configs_types.go
  api/v1alpha1/milvuscluster_types.go
  api/v1alpha1/milvuscluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/assets/templates/component.yaml.tmpl
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/samples/milvuscluster_config.yaml
  docs/CRD/milvus-cluster.md
  pkg/config/config.go
  pkg/controllers/components.go
  pkg/controllers/configmaps.go
  pkg/controllers/deployments.go
  pkg/controllers/status.go
Labels: lgtm, approved

#31 Fix helm values can't reset
  pkg/helm/helm.go
Labels: lgtm, approved

#34 Add CI workflow
  .github/workflows/ci.yml
Labels: lgtm, approved

#32 update pulsar values
  config/assets/charts/pulsar/values.yaml
Labels: lgtm, approved

#33 Build main-latest image when push to main branch
  .github/workflows/main-latest.yml
Labels: lgtm, approved

#35 update milvus config template
  .github/workflows/ci.yml
  config/assets/templates/milvus.yaml.tmpl
Labels: lgtm, approved

#36 Add status syncer
  main.go
  pkg/controllers/milvuscluster.go
  pkg/controllers/milvuscluster_controller.go
  pkg/controllers/status.go
  pkg/controllers/suite_test.go
Labels: lgtm, approved

#37 Add owners file
  OWNERS
Labels: lgtm, approved, size/S

#38 Fix map concurrent writes in UpdateStatus, add quick sync unhealthy status
  pkg/controllers/status.go
Labels: lgtm, approved, size/M

#39 Refactoring status syncer loop
  pkg/controllers/status.go
Labels: lgtm, approved, size/M

#41 Add Integration Test In CI workflow
  .github/workflows/ci.yml
  .gitignore
  Makefile
  test/min-mc.yaml
  test/sit.sh
Labels: lgtm, approved, size/L

#43 Add unittest for api/v1alpha1, add codecov action
  .github/workflows/ci.yml
  Makefile
  api/v1alpha1/milvuscluster_webhook.go
  api/v1alpha1/milvuscluster_webhook_test.go
  api/v1alpha1/values_types_test.go
  go.mod
Labels: lgtm, approved, size/L

#44 Add Dco check
  .github/workflows/dco.yml
Labels: lgtm, approved, size/XS

#45 Add unit test, clean up
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, approved, size/XL

#48 Add more unit test, use gomock
  .github/workflows/ci.yml
  .gitignore
  Makefile
  codcov.yaml
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/configmaps.go
  pkg/controllers/configmaps_test.go
  pkg/controllers/external_interfaces.go
  pkg/controllers/suite_test.go
  pkg/util/testing.go
  pkg/util/testing_test.go
Labels: lgtm, approved, size/XL
