Repository milvus-io/milvus-operator, pull requests merged in 2022-05, with the labels that each got.

#131 fix UpdateIngressStatus for MilvusCluster
  pkg/controllers/status_cluster.go
Labels: lgtm, approved, size/XS, ci-passed

#139 Update ci jobs
  .github/workflows/ci.yml
Labels: lgtm, approved, size/M, ci-passed

#140 Add combine s3, minio healthcheck
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/controllers/conditions.go
  pkg/controllers/conditions_test.go
  pkg/controllers/external_interfaces.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  pkg/external/kafka.go
  pkg/external/kafka_test.go
  pkg/external/minio.go
  pkg/external/minio_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, approved, size/XL, ci-passed

#141 Update metrics, export metrics port
  Makefile
  charts/milvus-operator/templates/deployment.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/checker.yaml
  config/manager/manager.yaml
  deploy/manifests/deployment.yaml
  go.mod
  main.go
  pkg/controllers/metrics.go
  pkg/controllers/setup.go
  pkg/controllers/status_cluster.go
  pkg/controllers/utils_test.go
Labels: lgtm, approved, size/M, ci-passed
