Repository milvus-io/milvus-operator, pull requests merged in 2022-07, with the labels that each got.

#155 Remove auth proxy, fix storage types enum
  charts/milvus-operator/templates/clusterrole.yaml
  charts/milvus-operator/templates/clusterrolebinding.yaml
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  config/rbac/kustomization.yaml
  deploy/manifests/deployment.yaml
Labels: lgtm, approved, size/L, ci-passed

#154 Refactoring set defaults, avoid restart dependencies when upgrade
  .github/mergify.yml
  .github/workflows/ci.yml
  Makefile
  apis/milvus.io/v1beta1/dependencies_types.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
  main.go
  pkg/controllers/dependencies.go
  pkg/controllers/dependencies_test.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/utils.go
  pkg/helm/helm.go
  pkg/helm/values/testing.go
  pkg/helm/values/values.go
  test/upgrade.sh
Labels: lgtm, approved, size/XL, ci-passed

#156 Add bump version script, add version print
  .gitignore
  Dockerfile
  Makefile
  apis/milvus.io/v1beta1/milvus_webhook.go
  main.go
  scripts/bump-version.sh
Labels: lgtm, approved, size/M, ci-passed

#157 Update milvus-helm to 3.0.28, bump version to 0.5.1
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/external/minio.go
  pkg/external/minio_test.go
Labels: lgtm, approved, size/M, ci-passed

#165 Fix milvus persistence example
  config/samples/milvus_persistence.yaml
Labels: lgtm, approved, size/XS, ci-passed

#164 Fix legacy synced annotation, fix pulsar value
  apis/milvus.io/v1beta1/milvus_webhook.go
  charts/milvus-operator/values.yaml
  local.Dockerfile
  pkg/controllers/dependencies.go
  pkg/controllers/dependencies_test.go
  pkg/controllers/milvuscluster/convert_controller.go
  pkg/external/minio.go
Labels: lgtm, approved, size/M, ci-passed

#163 Add ObservedGeneration, Status.Replicas use updated & ready replicas
  apis/milvus.io/v1beta1/milvus_types.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/milvus_controller.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
Labels: lgtm, approved, size/L, ci-passed

#166 bump version to v0.5.2
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, size/M, ci-passed

#167 Update milvus & helm version, bump version to 0.6.0
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#168 Revert "Update milvus & helm version, bump version to 0.6.0"
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#169 Fix signal not pass to milvus, milvus cannot gracefully shutdown
  scripts/run.sh
Labels: lgtm, approved, size/XS, ci-passed

#170 Add startup probe & remove initial dealy
  pkg/controllers/components.go
  pkg/controllers/deployment_updater.go
Labels: lgtm, approved, size/M, ci-passed

#171 Update Milvus to V2.1.0, milvus-helm to 3.1.2, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
  test/upgrade.sh
Labels: lgtm, approved, size/M, ci-passed
