Repository milvus-io/milvus-operator, pull requests merged in 2022-09, with the labels that each got.

#177 Bump version to 0.6.3, milvus-helm to 3.1.9
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, size/M, ci-passed

#178 Fix helm servicemonitor
  charts/milvus-operator/templates/servicemonitor.yaml
Labels: lgtm, approved, size/XS, ci-passed

#179 Support custom commands for milvus components
  .github/workflows/ci.yml
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/components.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployment_updater_test.go
  test/min-mc-feature.yaml
  test/min-milvus-feature.yaml
Labels: lgtm, approved, size/XL, ci-passed

#180 milvus default version to 2.1.1, bump version to 0.6.4
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
  scripts/bump-version.sh
Labels: lgtm, approved, size/M, ci-passed

#181 milvus to 2.1.2, milvus-helm to 3.1.11, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
  test/hello-milvus-job.yaml
  test/hello-milvus.py
  test/sit.sh
Labels: lgtm, approved, size/M, ci-passed

#182 Standalone use etcd, minio with 1 replica
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
Labels: lgtm, approved, size/S, ci-passed

#183 Milvus to v2.1.3, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#185 milvus to 2.1.4, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#184 Add podAnnotations, podLabels
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/utils.go
  test/min-mc-feature.yaml
  test/min-milvus-feature.yaml
  test/sit.sh
Labels: lgtm, approved, size/XL, ci-passed

#186 [kafka] update healthcheck
  go.mod
  go.sum
  pkg/external/kafka.go
  pkg/external/kafka_test.go
  test/min-mc-feature.yaml
  test/min-milvus-feature.yaml
Labels: lgtm, approved, size/L, ci-passed
