Repository milvus-io/milvus-operator, pull requests merged in 2022-08, with the labels that each got.

#172 Update docs for readme
  README.md
Labels: lgtm, approved, size/XS, ci-passed

#173 Update default milvus version to 2.1.1, update helm
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, size/M, ci-passed

#175 Support custom volume in milvus components
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/values_types.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/components.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployments_test.go
Labels: lgtm, approved, size/XXL, ci-passed
