Repository milvus-io/milvus-operator, pull requests merged in 2023-07, with the labels that each got.

#262 Bump version, default milvus version to 2.2.11
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#250 Optimize probing dependencies
  Makefile
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/webhook_suite_test.go
  go.mod
  go.sum
  pkg/controllers/component_condition.go
  pkg/controllers/component_condition_test.go
  pkg/controllers/conditions.go
  pkg/controllers/conditions_test.go
  pkg/controllers/endpoint_check_cache.go
  pkg/controllers/error_detail.go
  pkg/controllers/error_detail_test.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/milvusupgrade_controller.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
  pkg/controllers/suite_test.go
  pkg/controllers/utils.go
  pkg/external/kafka.go
  pkg/external/kafka_test.go
  pkg/external/minio.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, approved, size/XXL, ci-passed

#266 Support milvus restful port
  apis/milvus.io/v1beta1/components_types.go
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  pkg/controllers/components.go
  pkg/controllers/deployment_updater.go
Labels: size/M, do-not-merge/hold
