Repository milvus-io/milvus-operator, pull requests merged in 2023-08, with the labels that each got.

#268 Fix CI
  .github/workflows/ci.yml
  Makefile
  config/kind/kind-dev.yaml
  test/min-mc.yaml
  test/sit.sh
Labels: lgtm, approved, size/M, ci-passed

#269 Add maintaining metric status
  pkg/controllers/metrics.go
  pkg/controllers/milvus.go
  pkg/controllers/milvus_controller.go
Labels: lgtm, approved, size/S, ci-passed

#267 Support milvus restful port
  apis/milvus.io/v1beta1/components_types.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
Labels: lgtm, approved, size/M, ci-passed

#265 Support update standalone to cluster, optimize stopping
  .github/mergify.yml
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
  pkg/controllers/component_condition.go
  pkg/controllers/component_condition_test.go
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployments.go
  pkg/controllers/deployments_test.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/milvusupgrade_fsm_test.go
  pkg/controllers/services.go
  pkg/controllers/status_cluster.go
  pkg/controllers/utils.go
Labels: lgtm, approved, size/L, ci-passed

#256 Update crd reference doc, fix typo
  docs/CRD/milvus.md
Labels: documentation, lgtm, approved, size/L

#270 Bump version, default milvus version to 2.2.12
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#271 Bump version, default milvus version to 2.2.13
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#272 Support ordered rolling for v2.3+
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/dependency_graph.go
  pkg/controllers/deployment_updater_test.go
  pkg/provisioner/cert_manager.go
Labels: lgtm, approved, size/L, ci-passed

#274 Archived
  README.md
Labels: documentation, lgtm, approved, size/L
