Repository milvus-io/milvus-operator, pull requests merged in 2023-06, with the labels that each got.

#252 Bump version: milvus to 2.2.9, operator to 0.7.13
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#253 feat: Add PriorityClassName in Milvus CRDs
  apis/milvus.io/v1beta1/components_types.go
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  pkg/util/k8s_client_test.go
Labels: lgtm, approved, size/M, ci-passed

#254 Bump version, default milvus version to 2.2.10
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/templates/crds.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/L, ci-passed

#257 Add service port for sidecar
  apis/milvus.io/v1beta1/values_types.go
  pkg/controllers/components.go
  pkg/controllers/components_test.go
Labels: lgtm, approved, size/M, ci-passed

#258 Optimize httpget test
  pkg/util/util_test.go
Labels: lgtm, approved, size/S, ci-passed
