Repository milvus-io/milvus-operator, pull requests merged in 2023-05, with the labels that each got.

#244 Bump milvus version to 2.2.8
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#245 support sidecar&initcontainer for components
  .gitignore
  Makefile
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/components.go
  pkg/controllers/deployment_updater.go
Labels: lgtm, approved, size/XL, ci-passed

#249 Optimize status update
  go.mod
  pkg/controllers/status_cluster.go
Labels: lgtm, approved, size/S, ci-passed

#248 Add k8s qps burst config
  main.go
  pkg/controllers/suite_test.go
  pkg/manager/manager.go
Labels: lgtm, approved, size/S, ci-passed
