Repository milvus-io/milvus-operator, pull requests merged in 2023-02, with the labels that each got.

#210 Support active standby & rolling update for coords & standalone
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  test/min-mc-feature.yaml
  test/min-milvus-feature.yaml
Labels: lgtm, approved, size/L, ci-passed

#218 Add updating, stopped status
  README.md
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  config/samples/cluster_demo.yaml
  config/samples/demo.yaml
  deploy/manifests/deployment.yaml
  docs/CRD/milvus.md
  docs/administration/scale-a-milvus-cluster.md
  pkg/controllers/components.go
  pkg/controllers/conditions.go
  pkg/controllers/conditions_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployments.go
  pkg/controllers/metrics.go
  pkg/controllers/milvus.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/milvus_test.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
Labels: lgtm, approved, size/XL, ci-passed

#221 Milvus to 2.2.3, milvus-helm to 4.0.6, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, size/M, ci-passed

#220 rolling update, add condition for updating
  Makefile
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  config/samples/milvus_rolling_update.yaml
  deploy/manifests/deployment.yaml
  docs/CRD/milvus.md
  docs/administration/upgrade.md
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/conditions.go
  pkg/controllers/conditions_test.go
  pkg/controllers/dependency_graph.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployment_updater_test.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm, approved, size/XXL, ci-passed

#223 Helm chart now obeys imagePullSecrets value
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/templates/deployment.yaml
  charts/milvus-operator/templates/job.yaml
Labels: lgtm, approved, size/S, ci-passed

#225 Bump version to 0.7.6, update docs
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/templates/deployment.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/administration/upgrade.md
  docs/installation/installation.md
  scripts/bump-version.sh
Labels: lgtm, approved, size/M, ci-passed

#226 Update etcd to 3.5.5-2, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, size/M, ci-passed
